version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    python-packages:
      patterns:
        - "*"
  ignore:
    - dependency-name: "numpy"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
